# -*- coding: utf-8 -*-
"""core Python practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qUMcRIXoU79NNOu1Ua09vJzQuQcKZwze
"""

# 1. variable an dynamic typing
crew_count = 12
captain_name = "Nav"
is_sailing = True
run_per_person = 0.75

# check types
print(type(crew_count))
print(type(captain_name))


# 2. String
log_entry = " captain Nav entered the bridge at 06:00 "

# Common string operations
cleaned = log_entry.strip()
upper = cleaned.upper()
words = cleaned.split()
joined = "-".join(words)

hashed_password = "Nav123"
print(hashed_password.startswith("Nav"))

# f string (Best way to format)
report = f"{captain_name} has {crew_count} crew members"
print(report)

# 3. List
inventory = ["sword", "compass", "map", "map"]
inventory[0] = "cutlass"
inventory.append("run")
inventory.insert(1, "gold")
inventory.remove("map")
popped = inventory.pop()

inventory.sort()
length = len(inventory)
print(inventory)

# slicing (super powerful)
number = [0,1,2,3,4,5]
print(number[1:4])
print(number[:3])
print(number[3:])
print(number[::-1])

# 4. Tuple
# real life database row, api endpoint constant, day of week.

coordinates = (40.7128, 74.0060)
x, y = coordinates
print(x, y)

# single element tuple (comma needed)
single = ("captain",)
print(type(single))

# 5. Dictionary (key-value, like a real dictionary or json)
# real life api response, config setting user profile.

captain = {
    "name": "Nav",
    "age":45,
    "ships": ["Black pearl", "Flying Dutchman"],
    "is_active": True
}

print(captain["name"])
captain["rank"] = "Admiral"
captain["age"] = 45
del captain["is_active"]

# safe access
print(captain.get("salary", "Not disclosed"))

# Loop through dict
for key, value in captain.items():
  print(f"{key} -> {value}")

# 6. Set
visited_ports = {"Mumbai", "Singapore", "Dubai", "Mumbai"}

visited_ports.add("Capetown")
visited_ports.remove("Dubai")

other_ports = {"Singapore", "London", "New York"}
common = visited_ports.intersection(other_ports)
all_ports = visited_ports.union(other_ports)
print(f"Common ports: {common}")

# 7. Conditions (if elif else)
wind_speed = 45

if wind_speed > 45:
  action = "Reef the sails"
elif wind_speed > 30:
  action = "Reduce sail area"
elif wind_speed > 10:
  action = "full sail ahead"
else:
  action = "start the engine"

print(action)

# Ternary (one - liner)
status = "sailing" if wind_speed > 10 else "Anchored"

# 8. Loops (for and while)

# For loops - iterate
crew = ["jack", "will", "Elizabetti", "Barbosaa"]

for i, member in enumerate(crew):
  print(f"crew # {i + 1}: {member}")

# Iterating dictionary
for key, value in captain.items():
  print(f"{key} = {value}")

# While loop -
treasure_chest = 3
while treasure_chest > 0:
  print(f"Opening chest.. {treasure_chest} left.")
  treasure_chest -= 1

# break / continue
for port in ["Mumbai", "pirate bay", "London", "Tortuga"]:
  if port == "pirate bay":
    print("Danger! skipping..")
    continue
  if port == "Tortuga":
    print("Destination reached")
    break
  print(f"Sailing to {port}")

# 9. Functions
# Real life: Any repeated task. Calculated tax, validate email, send alert.

def calculate_supplies(days, crew_size):
  """ calculate water and food needed for voyage."""
  water_per_person = 2
  food_per_person = 1.5
  total_water = days * crew_size * water_per_person
  total_food = days * crew_size * food_per_person
  return total_water, total_food

water, food = calculate_supplies(10, 12)
print(f"need {water}L water and {food}kg food")

# Default parameter
def hail(name = "Sailor"):
  return f"Ahoy, {name}"

print(hail("Nav"))
print(hail())

# *args (multiple positional arguments)
def log_ports(*ports):
  for port in ports:
    print(f"port visited: {port}")
log_ports("Mumbai", "Dubai", "London")

#**kwargs (multiple keywords arguments)
def crew_details(**details):
  for key, value in details.items():
    print(f"{key}: {value}")
crew_details(name = "Name", rank = "Captain", ship = "Black pearl")

# 10. Lambda anonymous one liner function
# Real life: Quick sorting key, filter/map operation

coordinates_list = [(1,2), (4,1), (3,3)]
# Sort by y coordinates
coordinates_list.sort(key = lambda point: point[1])
print(coordinates_list)

# 11. list comprehension
# Real life: Transform api data, filter list create array quickly.

# Old way
squares_old = []
for i in range(10):
  squares_old.append(i**2)

# Pythonic way
squares = [i ** 2 for i in range(10)]
print(squares)

# with condition (even squares only)
even_squares = [i ** 2 for i in range(10) if i % 2 == 0]
print(even_squares)

# Dict comprehension
word_length = {word: len(word) for word in ["run", "gold", "treasure"]}
print(word_length)

# 12. Error Handling (try - except - finally)
def divide_treasure(total, pirates):
  try:
    share = total / pirates
  except ZeroDivisionError:
    return "need numbers, not string"
  else:
    return f"each pirates gets {share} gold coins"
  finally:
    print("Division attempt completed")

print(divide_treasure(1000, 5))
print(divide_treasure(1000, 0))

# 13. File handling

# Writing
with open("captains_log.txt", "w") as file:
  file.write("day 1: set sail from mumbai")
  file.write("day 2: calm seas. \n")

# reading
with open("captains_log.txt", "r") as file:
  content = file.read()
  print(content)

# Attending
with open("captains_log.txt", "a") as file:
          file.write("Day 3: spoted land")

# 14. OOP classes and objects (The big one)
class ship:
  """Blueprint for a ship"""
  fleet_count = 0

  def __init__(self, name, cannons):
    """Constructor - runs when object is created"""
    self.name = name
    self.cannons = cannons
    self.crew = []
    ship.fleet_count += 1

  def add_crew(self, sailor_name):
    """Instance method."""
    self.crew.append(sailor_name)
    return f"{sailor_name} boarded {self.name}"

  def fire_cannons(self):
    """Another instance method"""
    return f"{self.name} fires {self.cannons} cannons Booms"

  @classmethod
  def get_fleet_count(cls):
    """class method - works on class, not instance"""
    return f"Total ships in fleet: {cls.fleet_count}"

  @staticmethod
  def knot_tokmph(knots):
    """static method - utility function, no self/cls.cannons."""

  def __str__(self):
    """String representation"""
    return f"ship: {self.name}, cannons: {self.cannons}"

# using the class
pearl = ship("black pearl",32)
dutchman = ship("flying dutchman", 46)

print(pearl.add_crew("jack sparrow"))
print(pearl.fire_cannons())
print(ship.get_fleet_count())
print(ship.knot_tokmph(20))
print(pearl)

# 15. Inheritance
class pirateship(ship):
  def __init__(self, name, cannons, pirate_count):
    super().__init__(name, cannons)
    self.bounty = bounty

  def raise_jolly_roger(self):
    return f"{self.name} raises the jolly roger bounty: ${self.bounty}"


  def fire_cannons(self):
    return f"{self.name} fires All {self.cannons} cannons!"

  pirate_ship = pirateship("Queen Annes reve", 40, 1000000)
  print(pirate_ship.fire_cannons())
  print(pirate_ship.raise_jolly_roger())

# 16. Modules and imports

# Built in modules
import math
import random
from datetime import datetime

print(math.sqrt(64))
print(random.randint(1,10))
print(datatime.now().strftime("%Y-%m-%d %H:%M"))

# 17. Decorators (wrap function to add behaviour)

def captain_only(func):
  """Dcorators: only captain an exceute this functions."""
  def wrapper(user, *args, **kwargs):
    if user == "captain Nav"
      print("Access granted, captain")
      return func(*args, **kwargs)

    else:
      print("Access denied captain only")
    return wrapper

  @captain_only
  def launch_topedoes(target):
    print(f"Torpedoes to {target}")

  launch_torpedoes("Sailor")
  launch_torpedoes("Captain nav")

# 18. Generator memory effiicient

# Regular function return whole list (memory heavy)
def get_squares_list(n):
  result = []
  for i in range(n):
    result.append(i**2)
  return result

# Generator yields one at a time (memory efficient)
def get_squares_gen(n):
  for i in range(n):
    yield i ** 2

# using generator
for square in get_squares_gen(5):
  print(square, end = " ")
print()

# Generator expression (like list comprehension but with parenthesis)
gen = (i ** 2 for in range(1000000))
print(next(gen))
print(next(gen))

# 19. *args and **kwargs (deep dive)
def ship_manifest(captain, crew, **cargo):
  """Flexible function accepting any number of arguments."""
  print(f"captain: {captain}")
  print("crew")

  for member in crew:
    print(f" - {member}")
  print("cargo")
  for item, quality in cargo.items():
    print(f" - {item}: {quality} tons")

ship_manifest("Nav", "jack", "will", "elizabeth", run = 100, gold, spices = 25)

# Unpacking list / dict into function
settings = {"captain": "Nav", "cargo_type": "treasure"}
crew_list = ["Barbossa", "Gibbs"]
ship_manifest(*crew_list, **settings)

# 20. map, filter, reduce
numbers = [1,2,3,4,5,6,7,8,9,10]

# map apply function to all numbers
squared = list(map(lambda x: x % 2 == 0, numbers))
print(evens)

# reduce cumulative operation
from functools import reduce
sun_all = reduce(lambda acc, x: acc + x, numbers)
print(sum_all)

# 21. common built in function

data = [3,1,4,1,5,9,2,6]
print(max(data))
print(min(data))
print(sum(data))
print(sorted(data))
print(any([False, False, True]))
print(all([True, True, False]))

# Zip combine list
names = ["Nav", "jack", "will"]
ranks = ["captain", "private", "Balcksmith"]
for name, rank in zip(names, ranks):
  print(f"{name} is a {rank}")

# enumerate - index + value
for index, name in enumerate(names, start = 1)
print(f"{index}. {name}")

# 22. Type Hints
def calculate_distance(start: tuple[float, float],
                       end: tuple[float, float]) -> float:

  """ calculate euclidean distance between two conditions."""
  import math
  return math.sqrt((end[0]-start[0])**2 + (end[1]-start[1])**2)

  distance:float = calculate_distance((0, 0), (3,4))
  print(f"Distance: {distance}")

  # Type hints for variables
  crew_names: list[str] = ["Nav", "jack", "will"]
  captain_dict: dict[str, str | int] = {"name": "nav", "age": 45}

  # 23. content manager
  class Treasurechest:
    """custome context manager."""
    def __enter__(self):
      print("opening treasure chest...")
      return self

    def __exit__(self, exc_type, exc_val, exc_tb):
      print("closing treasure chest")
      if exc_type:
        print(f"Error occurred: {exc_val}")
      return False

    def take_gold(self, amount):
      print(f"taking {amount} gold coins")

    # Using custom context manger
    with TreasureChest() as chest:
      chest.take_gold(100)

# 24. dunder magic methid
class Cannonball:
  def __init__(self, weight):
    self.weight = weight

  def __add__(self, other):
    """Overload + operator."""
    return Cannonball(self,weight + other.weight)

  def __str__(self):
    return f"Cannonball({self.weight}kg)"

  def __len__()self:
    """Return weight as length."""
    return self.weight

ball1 = CannonBall(10)
ball2 = CannonBall(15)
ball3 = ball + ball2
print(ball3)
print(len(ball3))

# Common the captain pattern
# Simulating a real CLI tool pattern

def main():
  """entry point - like real application"""
  print("\n" + "=" * 50)
  print("python core training complete captain nav")
  print("=" *50)
  print(f"""
  summary of your fleet:
  - Ship: {pearl.name}
  - Cannons: {pearl.cannons}
  - fleet size: {ship.fleet_count}
  - crew: {len{pearl.crew}}
  - coordinates locked at: {coordinates}
        """

  )
if __name__ == "__main__":
  main()