# -*- coding: utf-8 -*-
"""Scikit - Learn | Traditional ML Garage .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A0Va1kUntwMvBkYd0Gy8Kyug9DNMPzzh
"""

"""
Comanche scikit learn Library

Topic Covered
1. Introduction to scikit-learn
2. Installing Scikit-learn
3. Loading Datasets
4. Data Preprocessing
5. Train-Test split
6. Feature Categorical Data
7. Encoding Categorical Data
8. Linear Regression
9. Logistic Regression
10. Decision Trees
11. Random Forest
12. K - nearest neighbors
13. Support Vector machine
14. Naive Bayes
15. Clustering
16. Dimensionality Reduction
17. Model Evaluation Metrics
18. Cross Valdation
19. Hyperparameters Tunning
20. Pipelines
21. Saving and Loading Models
22. Imabalanced Data
23. Feature Selection
24. End-to End Ml Workflow
25. Practice projects

"""
# 1. Introduction to scikit learn ========================================

"""
Scikit learn is one of the most popular python libraries for machine learning.

It provides:
- Classification algorithm
- Regression alogrithm
- Clustering Algorithm
- Data preparing tools
- Model evaluation tools
- Hyperparameters tuning
Pipelines

Scikit learn works very well with:
Numpy
Pandas
Matlotlib
seabron

"""
# Introduction scikit learn ==========================================

"""
Installing using:

pip istall scikit learn

check version:

"""
import sklearn

print("Scikit-Learn version:", sklearn.__version__)

# Step 3 Loading datasets =====================================

from sklearn.datasets import load_iris
#from sklearn.datasets import load_wines
from sklearn.datasets import load_diabetes

# Load iris
iris = load_iris()

print(type(iris))
print(iris.keys())

# Feature and target
X = iris.data
y = iris.target

print(X.data)
print(y.shape)

print("Feature Names:")
print(iris.feature_names)

print("Target Name")
print(iris.target_names)

# Step 4 Data preprocessing ==================================

import pandas as pd
import numpy as np

# Create Dataframe
iris_df = pd.DataFrame(X, columns = iris.feature_names)
iris_df["target"] = y

print(iris_df.head())

# Check missing values
print(iris_df.isnull().sum())

#Example mising value handling
sample_df = pd.DataFrame({
    "age": [20, 25, np.nan, 30],
    "salary": [3000, 40000, 50000, np.nan]

})

print(sample_df)

# Fill missing values
sample_df["age"] = sample_df["age"].fillna(sample_df["age"].mean())
sample_df["salary"] = sample_df["salary"].fillna(sample_df["salary"].median())

print(sample_df)

# 5 Train test Split ============================================

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2,
                                                    random_state=42)

print(X_train.shape)
print(X_test.shape)

# 6 Feature Scaling ==============================================

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(X_train_scaled.mean())

# MinMax scaling
minmax_scaler = MinMaxScaler()
X_train_scaled = minmax_scaler.fit_transform(X_train)

print(X_train_scaled[:5])

# 7 Encoding Categorical Data ================================
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# label Encoding
colors = ["red", "blue", "green", "red"]

label_encoder = LabelEncoder()
encoded_colors = label_encoder.fit_transform(colors)

print(encoded_colors)

# 8 Linear Regression =============================================

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Regression dataset
X_reg = load_diabetes().data
y_reg = load_diabetes().target

X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X_reg,
    y_reg,
    test_size = 0.2,
    random_state = 42
)

# create model
linear_model = LinearRegression()

# Train model
linear_model.fit(X_train_reg, y_train_reg)

# Prediction
prediction_reg = linear_model.predict(X_test_reg)

print(prediction_reg[:5])

# Evaluation metrics
mse = mean_squared_error(y_test_reg, prediction_reg)
r2 = r2_score(y_test_reg, prediction_reg)

print("MSE:", mse)
print("R2 Score:", r2)

# 9 Logistic Regression ==============================================
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Classification model
logistic_model = LogisticRegression(max_iter = 200) # Changed max_ter to max_iter

# train model
logistic_model.fit(X_train_scaled, y_train)

# Prediction for logistic regression
predictions_logistic = logistic_model.predict(X_test_scaled)

#Accuracy
accuracy_logistic = accuracy_score(y_test, predictions_logistic)
print("Accuracy:", accuracy_logistic)

# 10. decsion Tree ==========================================================
from sklearn.tree import DecisionTreeClassifier

# Model
decision_tree = DecisionTreeClassifier(
    criterion = "gini",
    max_depth = 3,
    random_state = 42
)

# Train model
decision_tree.fit(X_train, y_train)

# prediction
predictions_tree = decision_tree.predict(X_test)

print(predictions_tree[:10])

# 11. Random forest ==================================================

from sklearn.ensemble import RandomForestClassifier

random_forest = RandomForestClassifier(
    n_estimators = 100,
    max_depth = 3,
    random_state = 42
)
random_forest.fit(X_train, y_train)

predictions_rf = random_forest.predict(X_test)

accuracy_rf = accuracy_score(y_test, predictions_rf)
print("Random Forest Accuracy:", accuracy_rf)

# Feature importance
print(random_forest.feature_importances_)

# 12. K-Neighbors  ====================================================

from sklearn.neighbors import KNeighborsClassifier

# Model
knn_model = KNeighborsClassifier(n_neighbors = 3)

# Fit
knn_model.fit(X_train_scaled, y_train)

predictions_knn = knn_model.predict(X_test_scaled)

accuracy_knn = accuracy_score(y_test,predictions_knn)
print("KNN Accuracy:", accuracy_knn)

# 13 Support Vector machine =====================================

from sklearn.svm import SVC

svm_model = SVC(kernel = "linear") # Changed "Linear" to "linear" for consistency

svm_model.fit(X_train_scaled, y_train)

predictions_svm = svm_model.predict(X_test_scaled)

accuracy_svm = accuracy_score(y_test, predictions_svm)
print("SVM Accuracy:", accuracy_svm)

# 14. Naive Bayes =================================================

from sklearn.naive_bayes import GaussianNB # Removed extra dot

naive_bayes = GaussianNB()

naive_bayes.fit(X_train, y_train)

predictions_nb = naive_bayes.predict(X_test)

accuracy_nb = accuracy_score(y_test, predictions_nb)
print("Naive Bayes accuracy:", accuracy_nb)

# 15 Clustering ===================================================

from sklearn.cluster import KMeans

# Clustering model
kmeans_model = KMeans( # Renamed Kmeans to kmeans_model for variable consistency
    n_clusters = 3, # Changed n_cluster to n_clusters
    random_state = 42,
    n_init = 10
)

kmeans_model.fit(X) # Fit KMeans model

# CLuster labels
cluster_labels = kmeans_model.labels_

print(cluster_labels[:10])

print(kmeans_model.cluster_centers_)

# 16 Dimentionality reduction =========================================
from sklearn.decomposition import PCA

pca = PCA(n_components = 2)

X_pca = pca.fit_transform(X)

print(X_pca.shape)

# Explained variance
print(pca.explained_variance_ratio_)

# 17 Model Evaluation Metrics ======================================

from sklearn.metrics import classification_report, precision_score, recall_score, f1_score, confusion_matrix

# Example using random forest
# 'predictions' from Random Forest in section 11 was 'predictions_rf'
# Assuming predictions_rf is meant to be used here
predictions_eval = random_forest.predict(X_test)

# confusion metrics
cm = confusion_matrix(y_test, predictions_eval)
print("Confusion Matrix:\n", cm)
print("Classification Report:\n", classification_report(y_test, predictions_eval)) # Added classification_report print

# Metrics
precision = precision_score(y_test, predictions_eval, average = "weighted")
recall = recall_score(y_test, predictions_eval, average = "weighted")
f1 = f1_score(y_test, predictions_eval, average = "weighted")

print("precision:", precision)
print("Recall:", recall)
print("F1 score:", f1)

# 18. cross validation ===============================================

from sklearn.model_selection import cross_val_score

scores_cv = cross_val_score( # Renamed scoress to scores_cv for clarity
    random_forest,
    X,
    y,
    cv = 5,
    scoring = "accuracy"

)
print(scores_cv)
print("Average score:", scores_cv.mean())

# 19. Hyperparamters tuning =======================================
from sklearn.model_selection import GridSearchCV # Fixed 'model-selection' to 'model_selection'

parameters = {
    "n_estimators": [50, 100],
    "max_depth":[3,5,10]

}
# Grid Search
grid_search = GridSearchCV(
    estimator = RandomForestClassifier(random_state=42),
    param_grid = parameters,
    cv = 3,
    n_jobs = -1 # Added n_jobs for parallel processing

)

grid_search.fit(X_train, y_train) # Fit the grid search model

# train
print("Best parameters:")
print(grid_search.best_params_)

print("Best score:")
print(grid_search.best_score_)

# 20 Pipeline ===============================================
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("classifier", LogisticRegression(max_iter=200)) # Added max_iter for LogisticRegression

])
pipeline.fit(X_train, y_train)

predictions_pipeline = pipeline.predict(X_test)

print(predictions_pipeline[:10])

# 21 Saving and loading models =================================
import joblib

# save model
joblib.dump(random_forest, "random_forest_model.pkl")

# load model
loaded_model = joblib.load("random_forest_model.pkl")

# predict using loaded model
predictions_loaded = loaded_model.predict(X_test)

print(predictions_loaded[:5])

# 22 Imbalanced data =======================================
"""
# Techniques for imbalanced datasets:
1. Oversampling
2. Undersampling
3. Smote
4. Class weight
5. Evaluation metrics like F1-score

"""
# Example with class weights
weighted_model = LogisticRegression(class_weight="balanced", max_iter=200) # Fixed syntax for class_weight and added max_iter
weighted_model.fit(X_train_scaled, y_train)
predictions_weighted = weighted_model.predict(X_test_scaled)
print(classification_report(y_test, predictions_weighted))

# 23. Feature Selection =====================================
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2 # Fixed 'skelearn' to 'sklearn'

# select top features
selector_fs = SelectKBest(score_func = chi2, k = 2) # Renamed selectors to selector_fs

X_selected = selector_fs.fit_transform(X, y)

print(X_selected.shape)
print(selector_fs.scores_)